### ISSUE TITLE
Add script version

### ISSUE THREAD

**Issue by greganswer** [greganswer/mgit#5]
### Tasks

- [ ] Create a Version file and update it as needed (Maybe `__version__`)
- [ ] Reference the Version file in `setup.py`
- [ ] Reference the Version file in the [`--version` option](https://click.palletsprojects.com/en/7.x/api/#click.version_option)

### Resources

1.
